### ISSUE TITLE
registerWebInterface not working anymore

### ISSUE THREAD

**Issue by WebFreak001** [vibe-d/vibe.d#2440] opened 2020-05-03 21:16 UTC
Now with ldc 1.21 (dmd 2.091.1) the following error occurs when trying to call registerWebInterface:
```
../.dub/packages/vibe-d-0.9.0-alpha.4/vibe-d/web/vibe/web/web.d(197,6): Error: static assert:  "Instances may only be returned from parameter-less functions (__ctor)!"
source/app.d(428,29):        instantiated from here: registerWebInterface!(UploadManager, cast(MethodStyle)5)
```

Trying with project https://github.com/WebFreak001/ImageUploader but the rest interface class is just
```d
class Foo {
	this(MongoCollection collection) {}

	void getSomeFuncs() {}

	@path("*")
	void getFile(HTTPServerRequest req, HTTPServerResponse res) {}
}
```

it used to work with previous compilers, maybe some deprecation actually hitting now?

**Comment by Geod24** [comment] 2020-05-03 21:35
Duplicate of: https://github.com/vibe-d/vibe.d/issues/2438
There's a PR for it pending review from a maintainer.

**Closed by Geod24** 2020-05-03 21:35 UTC
