### ISSUE TITLE
Error in registerWebInterface

### ISSUE THREAD

**Issue by o3o** [vibe-d/vibe.d#2295] opened 2019-04-11 07:39 UTC
I've:
```d
/+ dub.json:
{
    "name": "test",
    "dependencies": {
        "vibe-d": "~>0.9"
    }
}
 +/
import vibe.vibe;
import std.experimental.logger;

shared static this() {
   auto router = new URLRouter;
   RecipeController ctrl = new RecipeController();
   router.registerWebInterface(ctrl);

   auto settings = new HTTPServerSettings;
   settings.bindAddresses = ["::1", "127.0.0.1"];
   settings.port = 8080;

   listenHTTP(settings, router);
}

struct Recipe {
   long id;
   string recipeName;
   string partNumber;
   string description;
   SysTime createdAt; // <<-- issue here
}

final class RecipeController {
   @path("/recipe/update") void postRecipeUpdate(Recipe r) {
      trace(r);
   }
}
```
So:
```
$ dub build
../../../.dub/packages/vibe-d-0.8.5/vibe-d/web/vibe/web/common.d(889,35): Error: generated function app.Recipe.opAssign(Recipe p) is not callable using argument types ()
../../../.dub/packages/vibe-d-0.8.5/vibe-d/web/vibe/web/common.d(889,35):        missing argument for parameter #1: Recipe p
../../../.dub/packages/vibe-d-0.8.5/vibe-d/web/vibe/web/web.d(956,40): Error: template instance `vibe.web.common.readFormParamRec!(Recipe)` error instantiating
../../../.dub/packages/vibe-d-0.8.5/vibe-d/web/vibe/web/web.d(207,34):        instantiated from here: handleRequest!("postRecipeUpdate", postRecipeUpdate, RecipeController)
source/app.d(7,31):        instantiated from here: registerWebInterface!(RecipeController, cast(MethodStyle)5)
/usr/bin/dmd failed with exit code 1.
```

If I remove `createdAt`:
```
struct Recipe {
   long id;
   string recipeName;
   string partNumber;
   string description;
   /// SysTime createdAt; 
}
```

It works! See [github example](https://github.com/o3o/vibe_systime_issue)

**Comment by Geod24** [comment] 2021-01-19 06:09
Added single package comment to make the example self-contained. Reproduced with v0.9.2.

**Comment by Geod24** [comment] 2021-01-19 06:45
Duplicate of https://github.com/vibe-d/vibe.d/issues/2411

**Closed by Geod24** 2021-01-19 06:45 UTC
Labels: bug, duplicate
