### ISSUE TITLE
improve the error message in JSONException

### ISSUE THREAD

**Issue by SingingBush** [vibe-d/vibe.d#1615] opened 2016-11-09 13:12 UTC
In `/vibe/data/json.d` is the following code:

```D
	//
	// deserialization
	//
	void readDictionary(Traits)(scope void delegate(string) field_handler)
	{
		enforceJson(m_current.type == Json.Type.object, "Expected JSON object, got "~m_current.type.to!string);
		auto old = m_current;
		foreach (string key, value; m_current) {
			m_current = value;
			field_handler(key);
		}
		m_current = old;
	}
```

which puts out the message *Expected JSON object, got array* when m_current.type isn't an object.

That's fair enough and would be fine if the data I was deserializing only had a few fields. Unfortunately for me I have about 100 fields that I now have to check to see which one caused the problem. Please can you get the error message to also display the name of the field which caused the problem.

**Comment by Geod24** [comment] 2021-07-01 00:16
Going to close this as a duplicate of #1961 (despite this issue being older) because the later has slightly more context and discussion.

**Closed by Geod24** 2021-07-01 00:16 UTC
