### ISSUE TITLE
Segmentation fault in vibe task invariant

### ISSUE THREAD

**Issue by SerialVelocity** [vibe-d/vibe.d#1053] opened 2015-04-01 22:26 UTC
Hey,

I've got a segmentation fault that rarely pops up in my program:

```
Process 983 stopped
* thread #2: tid = 0x41cc60, 0x00000001001ff7ee stream-downloader`D9invariant12_d_invariantFC6ObjectZv + 14, stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x00000001001ff7ee stream-downloader`D9invariant12_d_invariantFC6ObjectZv + 14
stream-downloader`D9invariant12_d_invariantFC6ObjectZv + 14:
-> 0x1001ff7ee:  movq   (%rax), %rbx
   0x1001ff7f1:  movq   0x60(%rbx), %rcx
   0x1001ff7f5:  testq  %rcx, %rcx
   0x1001ff7f8:  je     0x1001ff800               ; D9invariant12_d_invariantFC6ObjectZv + 32
(lldb) bt
* thread #2: tid = 0x41cc60, 0x00000001001ff7ee stream-downloader`D9invariant12_d_invariantFC6ObjectZv + 14, stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
  * frame #0: 0x00000001001ff7ee stream-downloader`D9invariant12_d_invariantFC6ObjectZv + 14
    frame #1: 0x0000000100105ade stream-downloader`D4vibe4core4task4Task7runningMxFNbNdZb + 158
    frame #2: 0x00000001000df513 stream-downloader`onSocketEvent + 883
    frame #3: 0x0000000100d8b5ac libevent-2.0.5.dylib`bufferevent_readcb + 293
    frame #4: 0x0000000100d82784 libevent-2.0.5.dylib`event_base_loop + 1858
    frame #5: 0x00000001000cb65f stream-downloader`D4vibe4core7drivers9libevent215Libevent2Driver12runEventLoopMFZi + 131
    frame #6: 0x00000001000c4905 stream-downloader`D4vibe4core4core12runEventLoopFZi + 225
    frame #7: 0x00000001000c702b stream-downloader`D4vibe4core4core16workerThreadFuncFZv + 119
    frame #8: 0x00000001001f2500 stream-downloader`D4core6thread6Thread3runMFZv + 28
    frame #9: 0x00000001001f1b74 stream-downloader`thread_entryPoint + 176
    frame #10: 0x00007fff8cde5268 libsystem_pthread.dylib`_pthread_body + 131
    frame #11: 0x00007fff8cde51e5 libsystem_pthread.dylib`_pthread_start + 176
    frame #12: 0x00007fff8cde341d libsystem_pthread.dylib`thread_start + 13
```

It's not really reproduceable though. My program is using 0.7.21. I'm not sure if it is still there in the latest version because it is so hard to reproduce. It would be great if you could look into it (or if you know whether it has already been fixed).

**Comment by SerialVelocity** [comment] 2015-04-01 22:26
It happens just after this exception:
```
object.Exception@../../../.dub/packages/vibe-d-0.7.21/source/vibe/core/drivers/libevent2_tcp.d(361): Operating on closed TCPConnection.
```

**Comment by SerialVelocity** [comment] 2015-04-01 22:43
Huh, somehow it happened again (this time on 0.7.23):
```
rror during transformer: object.Exception@../../../.dub/packages/vibe-d-0.7.23/source/vibe/core/drivers/libevent2_tcp.d(361): Operating on closed TCPConnection.
----------------
5   stream-downloader                   0x000000010000fa8f pure @safe bool std.exception.enforce!(bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) + 107
6   stream-downloader                   0x00000001000df0f1 void vibe.core.drivers.libevent2_tcp.Libevent2TCPConnection.checkConnected(bool) + 85
7   stream-downloader                   0x00000001000de3fe void vibe.core.drivers.libevent2_tcp.Libevent2TCPConnection.read(ubyte[]) + 114
8   stream-downloader                   0x00000001001543bf onBioRead + 111
9   libcrypto.0.9.8.dylib               0x00007fff893c7654 BIO_read + 100
10  libssl.0.9.8.dylib                  0x0000000100df5fab ssl3_read_n + 363
11  libssl.0.9.8.dylib                  0x0000000100df6b05 ssl3_read_bytes + 837
12  libssl.0.9.8.dylib                  0x0000000100df4b0c ssl3_read + 156
13  stream-downloader                   0x00000001001517b0 void vibe.stream.openssl.OpenSSLStream.read(ubyte[]) + 168
14  stream-downloader                   0x000000010014e29b void vibe.stream.counting.LimitedInputStream.read(ubyte[]) + 143
15  stream-downloader                   0x000000010014ed80 void vibe.stream.counting.EndCallbackInputStream.read(ubyte[]) + 192
16  stream-downloader                   0x0000000100057d6a shared(void function(shared(data.chunkinfo.ChunkInfo))) downloader.transformer.downloader.ChunkDownloader.onMessage + 486
17  stream-downloader                   0x0000000100058457 shared(void function()) stream.transformer.StreamTransformer!(data.chunkinfo.ChunkInfo, data.chunk.Chunk).StreamTransformer.onStart + 147
18  stream-downloader                   0x000000010005e7b3 shared(void function(shared(int))) stream.startable.StreamStartable.markWhenFinished + 95
19  stream-downloader                   0x0000000100054342 D4vibe4core4core33__T16makeTaskFuncInfoTDOFOiZvTOiZ16makeTaskFuncInfoFKDOFOiZvKOiZ12callDelegateFPS4vibe4core4core12TaskFuncInfoZv + 126
20  stream-downloader                   0x00000001000c6802 void vibe.core.core.CoreTask.run() + 366
21  stream-downloader                   0x00000001001fc681 void core.thread.Fiber.run() + 49
22  stream-downloader                   0x00000001001fc222 fiber_entryPoint + 98
23  ???                                 0x0000000000000000 0x0 + 0
[0x0000000000000000 - 0x0000000000000030)
[0x0000000000000030 - 0x0000000000000060)
[0x0000000000000060 - 0x0000000000000090)
[0x00000000000001f0 - 0x00000000000002a0)
[0x00000000000002a0 - 0x00000000000002b0)
[0x00000000000002b0 - 0x00000000000002c0)
[0x00000000000002c0 - 0x00000000000002d0)
[0x00000000000002d0 - 0x00000000000002e0)
[0x00000000000002e0 - 0x00000000000002f0)
[0x0000000000000450 - 0x0000000000000480)
[0x0000000000000480 - 0x00000000000004b0)
[0x00000000000004b0 - 0x00000000000004e0)
[0x00000000000004e0 - 0x0000000000000510)
[0x0000000000000510 - 0x0000000000000540)
[0x0000000000000540 - 0x0000000000000570)
[0x0000000000000570 - 0x00000000000005a0)
[0x00000000000005a0 - 0x00000000000005d0)
[0x00000000000005d0 - 0x0000000000000600)
[0x0000000000000600 - 0x0000000000000630)
[0x0000000000000630 - 0x0000000000000660)
[0x0000000000000660 - 0x000000000000068e)
Process 9197 stopped
* thread #2: tid = 0x43dac3, 0x00000001000e0d72 stream-downloader`onSocketEvent + 1058, stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x00000001000e0d72 stream-downloader`onSocketEvent + 1058
stream-downloader`onSocketEvent + 1058:
-> 0x1000e0d72:  movq   (%rdi), %r8
   0x1000e0d75:  callq  *0x20(%r8)
   0x1000e0d79:  jmp    0x1000e0ddd               ; onSocketEvent + 1165
   0x1000e0d7b:  movq   0x205d26(%rip), %rcx      ; TMP6825 + 8
(lldb) bt
[0x0000000000000000 - 0x0000000000000030)
[0x0000000000000030 - 0x0000000000000060)
[0x0000000000000060 - 0x000000000000008e)
[0x00000000000000e0 - 0x00000000000001f0)
[0x00000000000001f0 - 0x0000000000000200)
[0x0000000000000820 - 0x0000000000000828)
[0x0000000000000828 - 0x0000000000000830)
[0x0000000000000840 - 0x0000000000000848)
[0x0000000000000848 - 0x0000000000000850)
[0x0000000000000850 - 0x0000000000000880)
[0x0000000000000880 - 0x0000000000000888)
[0x0000000000000888 - 0x0000000000000890)
* thread #2: tid = 0x43dac3, 0x00000001000e0d72 stream-downloader`onSocketEvent + 1058, stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
  * frame #0: 0x00000001000e0d72 stream-downloader`onSocketEvent + 1058
    frame #1: 0x0000000100db35ac libevent-2.0.5.dylib`bufferevent_readcb + 293
    frame #2: 0x0000000100daa784 libevent-2.0.5.dylib`event_base_loop + 1858
    frame #3: 0x00000001000cd2bb stream-downloader`D4vibe4core7drivers9libevent215Libevent2Driver12runEventLoopMFZi + 131
    frame #4: 0x00000001000c58c2 stream-downloader`D4vibe4core4core12runEventLoopFZi + 254
    frame #5: 0x00000001000c82a9 stream-downloader`D4vibe4core4core16workerThreadFuncFNbZv + 141
    frame #6: 0x00000001001fb034 stream-downloader`D4core6thread6Thread3runMFZv + 28
    frame #7: 0x00000001001fa6a8 stream-downloader`thread_entryPoint + 176
    frame #8: 0x00007fff8cde5268 libsystem_pthread.dylib`_pthread_body + 131
    frame #9: 0x00007fff8cde51e5 libsystem_pthread.dylib`_pthread_start + 176
    frame #10: 0x00007fff8cde341d libsystem_pthread.dylib`thread_start + 13
```

**Comment by Geod24** [comment] 2021-06-24 09:43
Closing as it is the same root cause as #1241 which has been fixed. Feel free to comment / re-open if that is not the case.

**Closed by Geod24** 2021-06-24 09:43 UTC
