### ISSUE TITLE
Support UNIX sockets based on vibe.D's IO

### ISSUE THREAD

**Issue by aberba** [vibe-d/vibe.d#2101] opened 2018-03-06 08:13 UTC
UNIX sockets provide a way to securely connect in an enclosed/isolated environment without exposing connection externally. This is used in my our microservice infrastructure on: we connect to our db instance using a proxy and its the recommended approach in microservices. 

Its a very common security practice. The default approach on Google Cloud. I would do the same for any db I want to prevent external access to. If vibe.d doesn't support it then its missing a big piece of a puzzle.

Database libs like mysql-native could benefit from vibe.D's implementation to support UNIX socket connection that integrates well with vibe.d

**Comment by wilzbach** [comment] 2018-03-06 08:16
https://github.com/vibe-d/vibe.d/pull/2073

Is this what you are looking for? Your issue is pretty unspecific. Please clarify.

**Comment by aberba** [comment] 2018-03-08 20:52
The thing is we use the nodejs [mysql](https://github.com/mysqljs/mysql) package in production as the cloud db instance uses UNIX sockets (proxy) to connect to the database in as secure way when deployed. The docs there says under **Connection options** :

```
socketPath: The path to a UNIX domain socket to connect to. When used host and port are ignored.
```
It works as if both server process and database are on the same host machine. Its kind of like this code found in the issue you reference though:

```d
// examples/unix_socket_server/source/app.d 
auto settings = new HTTPServerSettings;
settings.bindAddresses = ["/tmp/vibe.sock"];
listenHTTP(settings, router);
```
The the `"/tmp/vibe.sock"` will be the path to the database socket connection. An example style of this approach is in the Google Cloud SQL Nodejs demo [here](https://cloud.google.com/appengine/docs/flexible/nodejs/using-cloud-sql) where they connect to the database using a proxy (UNIX socket connection). Here is a snippet from the page:

```js
const config = {
  user: process.env.SQL_USER,
  password: process.env.SQL_PASSWORD,
  database: process.env.SQL_DATABASE
};

if (process.env.INSTANCE_CONNECTION_NAME && process.env.NODE_ENV === 'production') {
  config.socketPath = `/cloudsql/${process.env.INSTANCE_CONNECTION_NAME}`;
}

// Connect to the database
const knex = Knex({
  client: 'mysql',
  connection: config
});
```

I requested UNIX socket connection support in mysql-native dub package and the dev mentioned vibe.d's IO something... needs to support such unix socket before mysql-native can support Unix socket IO compatible with vibe.d.

**Comment by Geod24** [comment] 2019-07-07 05:25
This looks like a duplicate of https://github.com/vibe-d/vibe.d/issues/500 which has been fixed (but not closed yet) AFAIK.

**Closed** 2020-01-10 05:05 UTC
