### ISSUE TITLE
vibe.d's http server returns vibe-core's version in http header

### ISSUE THREAD

**Issue by kubo39** [vibe-d/vibe.d#2617] opened 2021-10-06 11:07 UTC
vibe.d's http server returns vibe.core.core.vibeVersionString which is vibe-core's version in `Server` http header.
Is it expected?

```console
$ curl -I http://localhost:8080/
HTTP/1.1 200 OK
Server: vibe.d/1.21.0
Date: Wed, 06 Oct 2021 11:04:05 GMT
Keep-Alive: timeout=10
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
```

**Comment by Geod24** [comment] 2021-10-06 13:12
Duplicate of: https://github.com/vibe-d/vibe.d/issues/2404

**Closed by Geod24** 2021-10-06 13:12 UTC
