### ISSUE TITLE
InvalidMemoryOperationError

### ISSUE THREAD

**Issue by marcioapm** [vibe-d/vibe.d#1219] opened 2015-08-12 11:20 UTC
core.exception.InvalidMemoryOperationError@(0)
core.exception.InvalidMemoryOperationError@(0)
WARNING: HTTPClientResponse not fully processed before being finalized

This happens at least a couple times a day with only a couple of users using the webapp, so not really heavy load yet.

I'm not 100% sure it's related to vibed, but that warning is always following the crash, and our own codebase has no other dependencies, and we are not using classes at all.

Following this, the process hangs using 100% CPU.

This is 0.7.23, so it might have been fixed in 0.7.24, but I'm reporting it since there was nothing related in the changelog. I will deploy with 0.7.24 tomorrow and report back if that fixed it.

**Comment by etcimon** [comment] 2015-08-12 12:03
> Following this, the process hangs using 100% CPU.

I've been getting this as well because the InvalidMemoryOperationError gets called in a loop. You can try adding an asm { int 2; } like this here:
https://github.com/etcimon/druntime/commit/2ea784bafa6897fcdf47355f0afd0676b37627b1#diff-c3ee16974e487c9b8a70e34f4af39c25R539

Try compiling druntime with some of the fixes in that commit. Maybe we can get a stack trace from there.

From my experience, this usually occurs when you're leaving an HTTPClient or a HTTPClientResponse on the GC, if there was an allocation during the disconnection process. I would make sure you're using the scoped callbacks and not the `HTTPClientResponse requestHTTP(...)` function.

**Comment by marcioapm** [comment] 2015-08-12 12:21
Ah!

I am indeed using ```HTTPClientResponse requestHTTP(...)``` in a few places, so that could definitely be it.

This is nasty.

**Comment by etcimon** [comment] 2015-08-12 12:30
Yes, make sure you also call `res.dropBody()` if you don't read the response completely, you always have to make sure the response is completely drained or it could end up causing issues otherwise.

**Comment by marcioapm** [comment] 2015-08-12 12:31
Got it! Thanks!

**Comment by MartinNowak** [comment] 2015-11-21 20:15
Workaround if you're not interested in the response.

```d
// uses a scoped HTTPClientResponse
requestHTTP(url, (scope req) { /*...*/ }, (scope res) {});
// leaks a GC allocated HTTPClientResponse and causes the issue
requestHTTP(url, (scope req) { /*...*/ });
```

**Comment by Geod24** [comment] 2021-06-23 10:00
The root cause was that an `assert` in a dtor was triggered, and `assert` allocates prior to v2.097.0.
Duplicate of #2178 which is fixed.

**Closed by Geod24** 2021-06-23 10:00 UTC
