### ISSUE TITLE
Wrong error message from a harmless program

### ISSUE THREAD

**Issue by vporton** [vibe-d/vibe.d#2359] opened 2019-08-28 09:06 UTC
```d
import vibe.http.client;
import vibe.core.stream;

void main() {
    requestHTTP( "https://www.google.com",
    (scope req) {
    },
    (scope res) {
        res.readRawBody( (scope InputStream x) {});
    }
    );
}
```

prints meaningless error message:

```
Warning (thread: main): leaking eventcore driver because there are still active handles
   FD 6 (streamSocket)
Warning (thread: main): leaking eventcore driver because there are still active handles
   FD 6 (streamSocket)
```

**Comment by Geod24** [comment] 2020-08-24 00:36
Duplicate of #2245

**Closed by Geod24** 2020-08-24 00:36 UTC
