### ISSUE TITLE
Build fails with dmd master

### ISSUE THREAD

**Issue by John-Colvin** [vibe-d/vibe.d#1625] opened 2016-11-17 14:00 UTC
In `vibe.http.server` we have
```D
	version(VibeNoSSL) {} else {
		import std.traits : ReturnType;
		ReturnType!createTLSStreamFL tls_stream;
	}
```

but in `vibe.stream.tls`:
```D
auto createTLSStreamFL(Stream underlying, TLSContext ctx, TLSStreamState state, string peer_name = null, NetworkAddress peer_address = NetworkAddress.init)
{
	// This function has an auto return type to avoid the import of the TLS
	// implementation headers.  When client code uses this function the compiler
	// will have to semantically analyse it and subsequently will import the TLS
	// implementation headers.
	version (OpenSSL) {
		import vibe.utils.memory;
		import vibe.stream.openssl;
		static assert(AllocSize!TLSStream > 0);
		return FreeListRef!OpenSSLStream(underlying, cast(OpenSSLContext)ctx,
										 state, peer_name, peer_address);
	} else version (Botan) {
		import vibe.utils.memory;
		import vibe.stream.botan;
		return FreeListRef!BotanTLSStream(cast(ConnectionStream) underlying, cast(BotanTLSContext) ctx, state, peer_name, peer_address);
	} else assert(false, "No TLS support compiled in (VibeNoTLS)");
}
```

So if none of `VibeNoSSL`, `OpenSSL` or `Botan` is set, which seems to be the situation for me on macOS by default, you get `source/vibe/http/server.d(1640,32): Error: variable vibe.http.server.handleHTTPConnection.tls_stream variables cannot be of type void`

**Comment by s-ludwig** [comment] 2016-11-17 14:04
Duplicate of #1611

**Comment by John-Colvin** [comment] 2016-11-17 14:10
This is still happening for me with both `dub` and `vibe-d` master.

**Comment by s-ludwig** [comment] 2016-11-17 14:15
You need to remove dub.selections.json, because the bug caused openssl to be permanently de-selected.

**Comment by John-Colvin** [comment] 2016-11-17 15:02
Ok, so now I have this situation:

```
% tree .
.
├── dub.sdl
└── source
    └── app.d

1 directory, 2 files
% rm -rf ~/.dub .dub dub.selections.json

% cat dub.sdl
name "dubtest2"
dependency "vibe-d" version="~master"
john@MacBook-Pro-2 ~/tmp/dubTest2 % dub build
Fetching vibe-d ~master (getting selected version)...
Non-selected package libevent is available with version 2.0.1+2.0.16.
Non-selected package memutils is available with version 0.4.8.
Non-selected package libasync is available with version 0.7.9.
Use "dub upgrade" to perform those changes.
WARNING: A deprecated branch based version specification is used for the dependency vibe-d. Please use numbered versions instead. Also note that you can still use the dub.selections.json file to override a certain dependency to use a branch instead.
Non-optional dependency libasync of vibe-d:core not found in dependency tree!?.

% dub build
Fetching libevent 2.0.1+2.0.16 (getting selected version)...
Fetching memutils 0.4.8 (getting selected version)...
Fetching libasync 0.7.9 (getting selected version)...
WARNING: A deprecated branch based version specification is used for the dependency vibe-d. Please use numbered versions instead. Also note that you can still use the dub.selections.json file to override a certain dependency to use a branch instead.
Performing "debug" build using dmd for x86_64.
vibe-d:utils ~master: building configuration "library"...
vibe-d:data ~master: building configuration "library"...
vibe-d:core ~master: building configuration "libevent"...
vibe-d:crypto ~master: building configuration "library"...
vibe-d:stream ~master: building configuration "library"...
vibe-d:textfilter ~master: building configuration "library"...
vibe-d:diet ~master: building configuration "library"...
vibe-d:inet ~master: building configuration "library"...
vibe-d:http ~master: building configuration "library"...
../../.dub/packages/vibe-d-master/vibe-d/http/vibe/http/server.d(1641,32): Error: variable vibe.http.server.handleHTTPConnection.tls_stream variables cannot be of type void
dmd failed with exit code 1.
```

So it fails both times, but for different reasons :)

**Comment by s-ludwig** [comment] 2017-02-01 11:07
@John-Colvin: Sorry, I missed the last reply. I'll open a bug report against DUB for this. My suspicion is that it has something to do with using a `~master` dependency instead of a version based one.

**Comment by Geod24** [comment] 2021-06-23 07:32
This has been fixed on Vibe.d's side.

**Closed by Geod24** 2021-06-23 07:32 UTC
Labels: duplicate, external bug
